controller_manager_ns: controller_manager
controller_list:
  - name: vs087/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

  # - name: vs087/gripper_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints: [finger_A_joint, finger_B_joint, finger_C_joint]
