controller_manager_ns: controller_manager
controller_list:
  - name: vs087/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

  # - name: vs087/gripper_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints: [palm_finger_1_joint, finger_1_joint_1, finger_1_joint_2, finger_1_joint_3,
  #            palm_finger_2_joint, finger_2_joint_1, finger_2_joint_2, finger_2_joint_3,
  #            finger_middle_joint_1, finger_middle_joint_2, finger_middle_joint_3]
